# set up the default terminal
# ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vmware_desktop'
ENV["TERM"]="linux"

# set minimum version for Vagrant and install zypper package manager for Linux SUSE
Vagrant.require_version ">= 2.2.10"
Vagrant.configure("2") do |config|
  config.vm.provision "shell",
    inline: "sudo su - && zypper update && zypper install -y apparmor-parser"

  # Set the image for the vagrant box
  config.vm.box = "gyptazy/opensuse-tumbleweed-arm64"
  config.vm.box_version = "1.0.0"

  # Forward the ports from the guest VM to the local host machine
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 6111, host: 6111
  config.vm.network "forwarded_port", guest: 6112, host: 6112

  # Set the static IP for the vagrant box
  config.vm.network "private_network", ip: "192.168.50.4"
  # config.vm.network "bridged", :bridge => "ens160"

  # Configure the parameters for VirtualBox provider
  config.vm.provider "vmware_desktop" do |v|
    v.gui = false
    v.memory = "4096"
    v.cpus = 4
    v.vmx["ethernet0.pcislotnumber"] = "160"
  end
end

